service: ${file(package.json):name, 'marbles-challenge'}
frameworkVersion: '3'

plugins: ${file(../../serverless.common.yml):plugins}

custom: ${file(../../serverless.common.yml):custom}
provider: ${file(../../serverless.common.yml):provider}

functions:
  harvestbot-sheets-updates:
    handler: index.handler
    events:
      - httpApi:
          path: /harvestbot-sheets-updates
          method: GET